language: java

jdk:
    - oraclejdk8

env:
    # disable gradle daemon
    - GRADLE_OPTS="-Dorg.gradle.daemon=false"

install:
    - ./gradlew shadowJar

script:
    - ./gradlew jacocoTestReport

after_success:
    - bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy
    - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)