codecov:
  branch: master

coverage:
  precision: 3
  round: nearest
  range: "50...100"

  status:
    project:
      default:
        # TODO: change once in alpha (auto)
        target: 50%
        threshold: 1%
    patch:
      default:
        # TODO: change once in alpha (80%)
        target: 50%
        threshold: 1%

comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: new